version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres_test
    ports:
      - "3001:3001"
      - "9229:9229"

  postgres_test:
    container_name: authentication-postgres-test
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_HOST: postgres_test
      POSTGRES_USER: auth_admin
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: auth